# Generated by Django 2.2.10 on 2021-01-11 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0)),
                ('order_details', models.CharField(max_length=200)),
                ('order_date_time', models.DateTimeField()),
                ('fulfilled_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Kitchen', to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Counter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
