# Generated by Django 2.2.10 on 2021-01-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
