# Generated by Django 3.1.5 on 2021-01-12 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_app', '0004_auto_20210112_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Kitchen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='taken_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Counter', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
