# Generated by Django 3.1.5 on 2021-01-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_app', '0010_auto_20210112_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
