# Generated by Django 3.1.5 on 2021-01-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_app', '0011_auto_20210113_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('counter_staff', 'Counter Staff'), ('kitchen_staff', 'Kitchen Staff')], max_length=20),
        ),
    ]
